[package]
name = "lisp"
version = "0.1.0"
authors = ["Gabriel DORIATH DÖHLER <gabriel.doriath.dohler@ens.psl.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferr_os_librust = { git = "https://github.com/Sup3Legacy/FerrOS-librust" }
x86_64 = "*"
spin = "*"
uart_16550 = "*"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
